### PR TITLE
Fix placeholderColor when using basic placeholder text

### LINKED ISSUE #451: TextField Placeholder / Image Programatically
Hi, I'm facing a weird problem. When I create an AnimatableTextField via IB then all works as expected. In contrast when I create the same Textfield programatically and apply a left image and placeholder, then the latter don't get displayed... 

```
var emailField: AnimatableTextField = {
        var t = AnimatableTextField()
        t.translatesAutoresizingMaskIntoConstraints = false
        t.borderWidth = 1
        t.borderColor = .white
        t.borderSides = .bottom
        t.leftImage = #imageLiteral(resourceName: "email_text")
        t.placeholderColor = .white
        t.placeholderText = "eMail Address"
        t.tintColor = .white
        t.keyboardType = .emailAddress
        return t
    }()
```
Any Idea what I'm doing wrong?

PS: the Borders get displayed properly

### PR DESCRIPTION
**Pull request by tbaranes**
While trying to fix #451, I encountered a new issue: `placeholderColor` wasn't working 😨 
In the end, the issue was simply that I wasn't using `placeholderText` but `placeholder`. I don't know if that's the right fix, but I'm even wondering if `placeholderText` should exist in the first place. That PR will make `placeholderColor` available for `placeholderText` AND `placeholder`, but it will keep the current priority level: `placeholderText` > `placeholder`.

That also makes me wondering if it's really useful to have `placeholderText` since the property already exists natively and worked in interface builder. I have also the same question for `fillColor`. I have the impression that just bring confusion. If anyone is interested to discuss this, let's open a new issue about this.

### CODE REVIEW

**Comment by tbaranes** [comment]
@JakeLin Can you take a look at this? 🙃

**Review by JakeLin — APPROVED** [review]
👍  Cool, thanks for fixing that.

File: IBAnimatable/PlaceholderDesignable.swift [hunk 1]
```diff
@@ -18,7 +18,8 @@ public extension PlaceholderDesignable where Self: UITextField {
   var placeholderText: String? { get { return "" } set {} }
 
   public func configurePlaceholderColor() {
-    if let placeholderColor = placeholderColor, let placeholder = placeholder {
+    let text = placeholderText ?? placeholder
```
Comment (JakeLin) [inline IBAnimatable/PlaceholderDesignable.swift:21]: Sorry, hand on a sec. `var placeholderText: String? { get { return "" } set {} }` will never return `nil`. It just returns empty string. Will it be a problem?

**Comment by JakeLin** [comment]
I picked up the name`fillColor` because Sketch uses Fill Color, and I like that name 😁, I know that would cause priority problem. Shall we change it or leave for now?

File: IBAnimatable/PlaceholderDesignable.swift (hunk 1 above)
Comment (tbaranes) [reply IBAnimatable/PlaceholderDesignable.swift:21]: Doesn't seem to be an issue since it was working in the both sense when I tested it 🤔

**Comment by tbaranes** [comment]
I'm in favor to remove it, but not now. Let's keep it for a 5.0 release, it has been here for a while, it can stay here a little longer.

File: IBAnimatable/PlaceholderDesignable.swift (hunk 1 above)
Comment (JakeLin) [reply IBAnimatable/PlaceholderDesignable.swift:21]: If it's fine, we can merge it

Comment (SD10) [reply IBAnimatable/PlaceholderDesignable.swift:21]: `placeholderText` will always return an empty String, so if a user sets `Placeholder` in Interface Builder, the latter will never be considered. See [#499](https://github.com/IBAnimatable/IBAnimatable/pull/499)
